{% set name = "tensorflow-probability" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/{{ version }}.tar.gz
  sha256: 755d38db20a08d1b7d344ca00177e771525e473a6ab0922467b354da5df0a31e
  patches:
    - 0001-always-build-release.patch

build:
  skip: True  # [py38]
  number: 0
  script: 
    - rm -f BUILD
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6,<3.8
    - pip
  run:
    - python >=3.6,<3.8
    - pip
    - numpy >=1.16.0
    - six >=1.15.0
    - decorator >=4.4.2
    - cloudpickle >=1.2.2
    - dm-tree >=0.1.5
    - gast >=0.3.3
    - bazel >=3.7.0
    - setuptools >=41.0.

test:
  imports:
    - tensorflow_probability

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
    - oblute
    - rluria14
    - Tata17
